// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace XamChat.iOS
{
	public partial class ConversationsController : UITableViewController
	{
		public ConversationsController (IntPtr handle) : base (handle)
		{
		}
	}
}
