#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XamChat.Droid.Resource", IsApplication=true)]

namespace XamChat.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000f
			public const int addFriendMenu = 2131099663;
			
			// aapt resource value: 0x7f060001
			public const int conversationLastMessage = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int conversationUsername = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int conversationsList = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int friendName = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int friendsList = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int login = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int messageList = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int messageText = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int myMessageDate = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int myMessageText = 2131099659;
			
			// aapt resource value: 0x7f060006
			public const int password = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int sendButton = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int theirMessageDate = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int theirMessageText = 2131099661;
			
			// aapt resource value: 0x7f060005
			public const int username = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConversationListItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Conversations = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FriendListItem = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Friends = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Messages = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MyMessageListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TheirMessageListItem = 2130903047;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int ConversationsMenu = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int ErrorTitle = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Loading = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
